// Package class defines the classes entity and related value objects.
// It represents how data looks in the database or business rules.
package class

import (
	"github.com/james-wukong/school-schedule/internal/domain/school"
	"github.com/james-wukong/school-schedule/internal/domain/semester"
)

// Classes represents the classes table in PostgreSQL.
// It uses GORM tags to handle identity columns and automatic timestamps.
type Classes struct {
	// Identity column: GORM handles 'default' for values generated by the DB.
	ID int64 `gorm:"primaryKey;column:id;default:nextval('classes_id_seq');<-:false" json:"id"`

	// Foreign Key to Semester
	SemesterID int64               `gorm:"column:semester_id;not null;uniqueIndex:idx_semester_grade_class" json:"semester_id"`
	Semester   *semester.Semesters `gorm:"foreignKey:SemesterID;constraint:OnDelete:CASCADE" json:"semester,omitempty"`

	// Foreign Key to School
	SchoolID int64           `gorm:"column:school_id;not null;uniqueIndex:idx_rooms_school_code" json:"school_id"`
	School   *school.Schools `gorm:"foreignKey:SchoolID;constraint:OnDelete:CASCADE" json:"school,omitempty"`

	// Academic Details
	Grade        int    `gorm:"column:grade;not null;uniqueIndex:idx_semester_grade_class" json:"grade"`
	ClassName    string `gorm:"column:class;type:varchar(20);not null;uniqueIndex:idx_semester_grade_class" json:"class"`
	StudentCount int    `gorm:"column:student_count;default:40" json:"student_count"`
}

type ClassFilterEntity struct {
	SemesterID *int64
	SchoolID   *int64
	Grade      *int
	ClassName  *string
	Page       int
	Limit      int
}

func NewClass(schoolID, semesterID int64,
	grade, studentCount int,
	className string,
) *Classes {
	return &Classes{
		SchoolID:     schoolID,
		SemesterID:   semesterID,
		Grade:        grade,
		ClassName:    className,
		StudentCount: studentCount,
	}
}
