-- ============================================================================
-- SCHOOL SCHEDULING SYSTEM - PostgreSQL Schema
-- Version: 1.0
-- Tables: schools, teachers, students, courses, classrooms, timeslots, 
--         constraints, schedules, schedule_entries
-- ============================================================================

-- ============================================================================
-- SCHOOLS
-- ============================================================================

CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    website VARCHAR(255),
    established_year INT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_schools_code ON schools(code);
CREATE INDEX idx_schools_active ON schools(is_active);

-- ============================================================================
-- SUBJECTS
-- ============================================================================

CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(255) NOT NULL UNIQUE,
    required_lab BOOLEAN DEFAULT false,
    description TEXT,
    is_heavy BOOLEAN DEFAULT false,
	UNIQUE(school_id, code) -- Code unique within a school
);

CREATE INDEX idx_subjects_code ON subjects(code);
CREATE INDEX idx_subjects_school ON subjects(school_id);

-- ============================================================================
-- SEMESTERS
-- ============================================================================

CREATE TABLE semesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
	year INT NOT NULL,
	semester INT NOT NULL, -- "1->spring, 2->summer, 3->fall, 4->winter"
	start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    UNIQUE(school_id, year, semester)
);

CREATE INDEX idx_semesters_school ON semesters(school_id);

-- ============================================================================
-- TIMESLOTS
-- ============================================================================

CREATE TABLE timeslots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
    day_of_week INT NOT NULL, -- 'Monday->1', 'Tuesday->2', etc
    start_time TIME NOT NULL,
	end_time TIME NOT NULL,
    UNIQUE(semester_id, day_of_week, start_time)
);

CREATE INDEX idx_timeslots_school ON timeslots(semester_id);
CREATE INDEX idx_timeslots_day ON timeslots(day_of_week);

-- ============================================================================
-- TEACHERS
-- ============================================================================

CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    hire_date DATE NOT NULL,
    employment_type VARCHAR(50), -- 'Full-time', 'Part-time', 'Contract'
    max_classes_per_day INT DEFAULT 5,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(school_id, employee_id)
);

CREATE INDEX idx_teachers_school ON teachers(school_id);
CREATE INDEX idx_teachers_email ON teachers(email);
CREATE INDEX idx_teachers_active ON teachers(is_active);

-- ============================================================================
-- TEACHER - SUBJECTS
-- ============================================================================

CREATE TABLE teacher_subjects (
    teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,

    PRIMARY KEY (teacher_id, subject_id)
);

-- ============================================================================
-- TEACHER - TIMESLOTS
-- ============================================================================

CREATE TABLE teacher_timeslots (
    teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    timeslot_id BIGINT NOT NULL REFERENCES timeslots(id) ON DELETE CASCADE,

    PRIMARY KEY (teacher_id, timeslot_id)
);

-- ============================================================================
-- STUDENTS
-- ============================================================================

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    student_number VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(20),
    blood_group VARCHAR(10),
    admission_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(school_id, student_number)
);

CREATE INDEX idx_students_school ON students(school_id);
CREATE INDEX idx_students_admission ON students(student_number);
CREATE INDEX idx_students_active ON students(is_active);

-- ============================================================================
-- ROOMS
-- ============================================================================

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
    grade INT NOT NULL,
    class VARCHAR(20) NOT NULL,
    student_count INT DEFAULT 40,
    UNIQUE(semester_id, grade, class)
);

CREATE INDEX idx_classes_semesters ON classes(semester_id);

-- ============================================================================
-- ROOMS
-- ============================================================================

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    room_type VARCHAR(50), -- 'Classroom', 'Lab', 'Auditorium', 'Library'
    capacity INT DEFAULT 40,
    floor_number INT,
    building VARCHAR(100),
    available_days VARCHAR(50), -- 'Monday,Tuesday,Wednesday,Thursday,Friday'
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(school_id, code)
);

CREATE INDEX idx_rooms_school ON rooms(school_id);
CREATE INDEX idx_rooms_type ON rooms(room_type);
CREATE INDEX idx_rooms_active ON rooms(is_active);

-- ============================================================================
-- ROOM - TIMESLOTS
-- ============================================================================

CREATE TABLE room_timeslots (
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    timeslot_id BIGINT NOT NULL REFERENCES timeslots(id) ON DELETE CASCADE,

    PRIMARY KEY (room_id, timeslot_id)
);

-- ============================================================================
-- REQUIREMENTS
-- ============================================================================

CREATE TABLE requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
	weekly_sessions INT NOT NULL DEFAULT 1,
	min_day_gap INT NOT NULL DEFAULT 0,
	preferred_days VARCHAR(100) DEFAULT NULL, -- 1,2,3,4,5 separated by ,
    UNIQUE(subject_id, teacher_id, class_id)
);

CREATE INDEX idx_requirements_subject ON requirements(subject_id);
CREATE INDEX idx_requirements_teacher ON requirements(teacher_id);
CREATE INDEX idx_requirements_class ON requirements(class_id);

-- ============================================================================
-- SCHEDULES
-- ============================================================================
CREATE TYPE schedule_status_enum AS ENUM ('Draft', 'Published', 'Active', 'Archived');

CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    school_id BIGINT NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
	requirement_id BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,
	room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
	timeslot_id BIGINT NOT NULL REFERENCES timeslots(id) ON DELETE CASCADE,
    status schedule_status_enum DEFAULT 'Draft', -- 'Draft', 'Published', 'Active', 'Archived'
	version NUMERIC(10,2) DEFAULT 1.00,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

	UNIQUE(school_id, room_id, timeslot_id),
    UNIQUE(school_id, requirement_id, timeslot_id)
);

CREATE INDEX idx_schedules_school ON schedules(school_id);
CREATE INDEX idx_schedules_requirement ON schedules(requirement_id);
CREATE INDEX idx_schedules_room ON schedules(room_id);
CREATE INDEX idx_schedules_timeslot ON schedules(timeslot_id);
CREATE INDEX idx_schedules_status ON schedules(status);

-- ============================================================================
-- VIEWS FOR EASY QUERYING
-- ============================================================================

-- Teacher Daily Schedule
CREATE OR REPLACE VIEW view_teacher_schedules AS
SELECT 
    t.id AS teacher_id,
    t.first_name || ' ' || t.last_name AS teacher_name,
    sub.name AS subject_name,
    sub.code AS subject_code,
    cl.grade || '-' || cl.class AS class_name,
    r.name AS room_name,
    r.building,
    ts.day_of_week,
    ts.start_time,
    ts.end_time,
    s.status AS schedule_status
FROM schedules s
JOIN requirements req ON s.requirement_id = req.id
JOIN teachers t ON req.teacher_id = t.id
JOIN subjects sub ON req.subject_id = sub.id
JOIN classes cl ON req.class_id = cl.id
JOIN rooms r ON s.room_id = r.id
JOIN timeslots ts ON s.timeslot_id = ts.id
WHERE t.is_active = true;

-- Class Schedule Summary -> Timetable per class
CREATE OR REPLACE VIEW v_class_schedule AS
SELECT 
    c.id AS class_id,
    c.grade,
    c.class,
    sub.name AS subject,
    t.first_name || ' ' || t.last_name AS teacher,
    ts.day_of_week,
    ts.start_time,
    ts.end_time,
    r.name AS room
FROM schedules sc
JOIN requirements req ON req.id = sc.requirement_id
JOIN classes c ON c.id = req.class_id
JOIN subjects sub ON sub.id = req.subject_id
JOIN teachers t ON t.id = req.teacher_id
JOIN timeslots ts ON ts.id = sc.timeslot_id
JOIN rooms r ON r.id = sc.room_id;

-- Class/Section Master Schedule
CREATE OR REPLACE VIEW view_class_timetables AS
SELECT 
    cl.id AS class_id,
    cl.grade,
    cl.class,
    ts.day_of_week,
    ts.start_time,
    ts.end_time,
    sub.name AS subject_name,
    t.first_name || ' ' || t.last_name AS teacher_name,
    r.name AS room_name
FROM schedules s
JOIN requirements req ON s.requirement_id = req.id
JOIN classes cl ON req.class_id = cl.id
JOIN subjects sub ON req.subject_id = sub.id
JOIN teachers t ON req.teacher_id = t.id
JOIN rooms r ON s.room_id = r.id
JOIN timeslots ts ON s.timeslot_id = ts.id;


-- ============================================================================
-- VIEWS FOR ANALYTIC QUERYING
-- ============================================================================

-- Teacher Workload Analysis
CREATE OR REPLACE VIEW view_teacher_workload_stats AS
SELECT 
    t.id AS teacher_id,
    t.first_name || ' ' || t.last_name AS teacher_name,
    t.max_classes_per_day,
    COUNT(s.id) AS total_weekly_sessions,
    -- Calculate total hours using interval arithmetic (PostgreSQL)
    SUM(EXTRACT(EPOCH FROM (ts.end_time - ts.start_time)) / 3600)::NUMERIC(10,2) AS total_weekly_hours,
    COUNT(DISTINCT ts.day_of_week) AS work_days_count
FROM teachers t
LEFT JOIN requirements req ON t.id = req.teacher_id
LEFT JOIN schedules s ON req.id = s.requirement_id
LEFT JOIN timeslots ts ON s.timeslot_id = ts.id
WHERE t.is_active = true
GROUP BY t.id, t.first_name, t.last_name, t.max_classes_per_day;

-- Room Utilization Rate
CREATE OR REPLACE VIEW view_room_utilization AS
WITH total_slots AS (
    SELECT semester_id, COUNT(*) as slot_count 
    FROM timeslots 
    GROUP BY semester_id
)
SELECT 
    r.id AS room_id,
    r.name AS room_name,
    r.room_type,
    r.capacity,
    sem.semester,
    COUNT(s.id) AS occupied_slots,
    ts_total.slot_count AS total_available_slots,
    ROUND((COUNT(s.id)::DECIMAL / ts_total.slot_count) * 100, 2) AS utilization_percentage
FROM rooms r
CROSS JOIN semesters sem
JOIN total_slots ts_total ON sem.id = ts_total.semester_id
LEFT JOIN schedules s ON r.id = s.room_id
LEFT JOIN timeslots ts ON s.timeslot_id = ts.id AND ts.semester_id = sem.id
GROUP BY r.id, r.name, r.room_type, r.capacity, sem.semester, ts_total.slot_count;

-- Conflict Detector: Teacher conflict
CREATE OR REPLACE VIEW view_schedule_audit_conflicts AS
SELECT 
    ts.day_of_week,
    ts.start_time,
    'Teacher Double-Booked' AS conflict_reason,
    t.first_name || ' ' || t.last_name AS entity_name,
    STRING_AGG(sub.name || ' (' || cl.grade || '-' || cl.class || ')', ' vs ') AS conflicting_sessions
FROM schedules s
JOIN requirements req ON s.requirement_id = req.id
JOIN teachers t ON req.teacher_id = t.id
JOIN subjects sub ON req.subject_id = sub.id
JOIN classes cl ON req.class_id = cl.id
JOIN timeslots ts ON s.timeslot_id = ts.id
GROUP BY ts.day_of_week, ts.start_time, t.id, t.first_name, t.last_name
HAVING COUNT(s.id) > 1;

-- Conflict Detector: Room Conflict
CREATE OR REPLACE VIEW v_room_conflicts AS
SELECT
    school_id,
    room_id,
    timeslot_id,
    COUNT(*) AS conflict_count
FROM schedules
GROUP BY school_id, room_id, timeslot_id
HAVING COUNT(*) > 1;

-- ============================================================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================================================

-- Insert sample school
INSERT INTO schools (name, code, city, country)
VALUES 
('Springfield High School', 'SHS', 'Springfield', 'USA'),
('Riverdale Academy', 'RDA', 'Riverdale', 'USA');

-- Insert sample semesters
INSERT INTO semesters (school_id, year, semester, start_date, end_date)
VALUES
(1000, 2025, 1, '2025-02-18', '2025-06-30'),
(1000, 2025, 2, '2025-09-01', '2026-02-01');

-- Insert sample subjects
INSERT INTO subjects (school_id, name, code, required_lab, is_heavy)
VALUES
(1000, 'Mathematics', 'MATH', false, true),
(1000, 'Chinese', 'CHI', false, true),
(1000, 'Science', 'SCI', false, true),
(1000, 'Music', 'MUS', false, false),
(1000, 'Physics Education', 'PE', true, false),
(1000, 'History', 'HIS', false, false),
(1000, 'English', 'ENG', false, true);

-- Insert sample teachers
INSERT INTO teachers (school_id, employee_id, first_name, last_name, hire_date)
VALUES
(1000, 100110, 'John', 'Doe', '2020-01-01'),
(1000, 100111, 'Jane', 'Smith', '2021-02-01'),
(1000, 100212, 'Alice', 'Vough', '2019-03-01'),
(1000, 100213, 'Frank', 'Brown', '2019-03-01'),
(1000, 100214, 'David', 'Mash', '2019-03-01'),
(1000, 100215, 'Dave', 'Blow', '2019-03-01'),
(1000, 100216, 'Eve', 'Sigh', '2019-03-01'),
(1000, 100217, 'Jack', 'Goha', '2019-03-01'),
(1000, 100218, 'Salvana', 'Doe', '2019-03-01'),
(1000, 100219, 'Nick', 'Vue', '2019-03-01');

-- Insert sample students
INSERT INTO students (school_id, student_number, first_name, last_name, admission_date)
VALUES
(1000, 'S001', 'Tom', 'Hanks', '2023-09-01'),
(1000, 'S002', 'Emma', 'Watson', '2023-09-01'),
(1001, 'S001', 'Chris', 'Evans', '2023-09-01');

-- Insert sample classes
INSERT INTO classes (semester_id, grade, class)
VALUES
(1001, 1, 'A'),
(1001, 1, 'B'),
(1001, 1, 'C'),
(1001, 2, 'A'),
(1001, 2, 'B'),
(1001, 2, 'C');

-- Insert sample rooms
INSERT INTO rooms (school_id, code, name, room_type)
VALUES
(1000, 'R101', 'Room 101', 'Regular'),
(1000, 'R102', 'Room 102', 'Regular'),
(1000, 'R103', 'Room 103', 'Regular'),
(1000, 'R201', 'Room 201', 'Regular'),
(1000, 'R202', 'Room 202', 'Regular'),
(1000, 'R203', 'Room 203', 'Regular'),
(1000, 'LAB1', 'Physics Lab', 'Lab'),
(1000, 'GYM1', 'Gymnastic', 'Gym');

-- Insert sample timeslots
INSERT INTO timeslots (semester_id, day_of_week, start_time, end_time)
VALUES
(1001, 1, '09:00', '09:45'),
(1001, 1, '10:00', '10:45'),
(1001, 1, '11:00', '11:45'),
(1001, 1, '13:00', '13:45'),
(1001, 1, '14:00', '14:45'),
(1001, 1, '15:00', '15:45'),
(1001, 2, '09:00', '09:45'),
(1001, 2, '10:00', '10:45'),
(1001, 2, '11:00', '11:45'),
(1001, 2, '13:00', '13:45'),
(1001, 2, '14:00', '14:45'),
(1001, 2, '15:00', '15:45'),
(1001, 3, '09:00', '09:45'),
(1001, 3, '10:00', '10:45'),
(1001, 3, '11:00', '11:45'),
(1001, 3, '13:00', '13:45'),
(1001, 3, '14:00', '14:45'),
(1001, 3, '15:00', '15:45'),
(1001, 4, '09:00', '09:45'),
(1001, 4, '10:00', '10:45'),
(1001, 4, '11:00', '11:45'),
(1001, 4, '13:00', '13:45'),
(1001, 4, '14:00', '14:45'),
(1001, 4, '15:00', '15:45'),
(1001, 5, '09:00', '09:45'),
(1001, 5, '10:00', '10:45'),
(1001, 5, '11:00', '11:45'),
(1001, 5, '13:00', '13:45'),
(1001, 5, '14:00', '14:45'),
(1001, 5, '15:00', '15:45');

-- Insert sample teacher-subjects
INSERT INTO teacher_subjects (teacher_id, subject_id)
VALUES
(1000, 1000),
(1001, 1000),
(1002, 1001),
(1003, 1001),
(1004, 1002),
(1005, 1002),
(1006, 1003),
(1007, 1003),
(1008, 1004),
(1009, 1005);

-- Insert sample teacher-timeslots
INSERT INTO teacher_timeslots (teacher_id, timeslot_id)
VALUES
(1000, 1000),
(1000, 1001),
(1001, 1000);

-- Insert sample room-timeslots
INSERT INTO room_timeslots (room_id, timeslot_id)
VALUES
(1000, 1000),
(1001, 1001),
(1002, 1002);

-- Insert sample requirements
INSERT INTO requirements (subject_id, teacher_id, class_id, weekly_sessions)
VALUES
(1000, 1000, 1000, 3),
(1001, 1001, 1001, 2),
(1002, 1002, 1002, 2);

-- Insert sample schedules
INSERT INTO schedules (school_id, requirement_id, room_id, timeslot_id, status)
VALUES
(1000, 1000, 1000, 1000, 'Draft'),
(1000, 1001, 1001, 1001, 'Published'),
(1001, 1002, 1002, 1002, 'Active');


-- ============================================================================
-- END OF SCHEMA
-- ============================================================================

COMMIT;

