BEGIN;

-- ============================================================================
-- SAMPLE FILES
-- ============================================================================

CREATE TABLE sample_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    UNIQUE(filename)
);

COMMIT;